### ISSUE TITLE
Should use save instead of update

### ISSUE THREAD

**Issue by malhal** [4thirteen/resource-controller#1]
If you save the model instead of doing an update query then you benefit from model validation and events.

**Comment by matt-daneshvar** [comment]
The underlying [implementation](https://github.com/laravel/framework/blob/f6fe8b2492ede0b882607cabc1af40e5765ef133/src/Illuminate/Database/Eloquent/Model.php#L1423-L1430) for `update` on Eloquent models, fills the model and calls `save`.

```
public function update(array $attributes = [], array $options = [])
{
    if (! $this->exists) {
        return false;
    }

    return $this->fill($attributes)->save($options);
}
```

Any events or validations relying on `save` should work just fine.

**Comment by malhal** [comment]
apologies was looking at several of these resource controller implementations late last night and got mixed up.

**Comment by matt-daneshvar** [comment]
No problem at all.. Thanks for taking the time to share your thoughts anyways.
